project:
  type: website

website:
  title: "Raelynn Cui"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/raelynncui
      - icon: linkedin
        href: https://www.linkedin.com/in/raelynncui
format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto


